export interface Skills {
    'Athletics':        0 | 1 | 2,
    'Acrobatics':       0 | 1 | 2,
    'Sleight of hand':  0 | 1 | 2,
    'Stealth':          0 | 1 | 2,
    'Arcana':           0 | 1 | 2,
    'History':          0 | 1 | 2,
    'Investigation':    0 | 1 | 2,
    'Nature':           0 | 1 | 2,
    'Religion':         0 | 1 | 2,
    'Animal handling':  0 | 1 | 2,
    'Insight':          0 | 1 | 2,
    'Medicine':         0 | 1 | 2,
    'Perception':       0 | 1 | 2,
    'Survival':         0 | 1 | 2,
    'Deception':        0 | 1 | 2,
    'Intimidation':     0 | 1 | 2,
    'Performance':      0 | 1 | 2,
    'Persuasion':       0 | 1 | 2
}